### ISSUE TITLE
Queue full exception with v2.3.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sleyzerzon/spymemcached#176]
```
spymemcache 2.3.1 
memcached 1.4.4
Both of the above on Linux version 2.6.18-164.15.1.0.1.el5 
(mockbuild@ca-build9.us.oracle.com)

When I test executing mc.set(x,y) for a large times, e.g 
35 Million, Following exception would be thrown all the time. I saw Issue#38 
for the same exception but said fixed in v2.2. Though I'm using 2.3.1 still 
facing same issue. Any help would be higly appreciated. 

java.lang.IllegalStateException: Queue full
    at java.util.AbstractQueue.add(AbstractQueue.java:71)
    at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:209)
    at net.spy.memcached.protocol.TCPMemcachedNodeImpl.addOp(TCPMemcachedNodeImpl.java:241)
    at net.spy.memcached.MemcachedConnection.addOperation(MemcachedConnection.java:553)
    at net.spy.memcached.MemcachedConnection.addOperation(MemcachedConnection.java:543)
    at net.spy.memcached.MemcachedClient.addOp(MemcachedClient.java:256)
    at net.spy.memcached.MemcachedClient.asyncStore(MemcachedClient.java:287)
    at net.spy.memcached.MemcachedClient.set(MemcachedClient.java:612)
    at net.spy.memcached.MemcachedClient.set(MemcachedClient.java:646)
```

Original issue reported on code.google.com by `lakshmip...@gmail.com` on 4 May 2011 at 7:28

**Comment by iddolpm** [comment]
See also issue #192
