### ISSUE TITLE
Rare total failure caused by input queue full

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sleyzerzon/spymemcached#192]
```
What version of the product are you using? On what operating system?
Memcache 2.7 on Linux (EC2 instance using the Ubuntu Maverick AMI ami-08f40561)

Tell me more...

I think that there is a state the memcache client can get into where all 
network traffic ceases and all calls hang for ten seconds, then throw 
IllegalStateException.

I got our program into this state twice over the weekend by running some 
aggressive loadtests with some memcache servers that were ~ 0.5ms away from the 
client machine; I have not since then been able to reproduce this failure in an 
environment where I could hook up a debugger to see what's going on.

The observed exception is this:

java.lang.IllegalStateException: Timed out waiting to add 
net.spy.memcached.protocol.ascii.StoreOperationImpl@727b65b4(max wait=10000ms)
at 
net.spy.memcached.protocol.TCPMemcachedNodeImpl.addOp(TCPMemcachedNodeImpl.java:
292)
at 
net.spy.memcached.MemcachedConnection.addOperation(MemcachedConnection.java:739)
at 
net.spy.memcached.MemcachedConnection.addOperation(MemcachedConnection.java:719)
at net.spy.memcached.MemcachedClient.addOp(MemcachedClient.java:410)
at net.spy.memcached.MemcachedClient.asyncStore(MemcachedClient.java:447)
at net.spy.memcached.MemcachedClient.set(MemcachedClient.java:868)
... (our code after this)

Meanwhile, the IO thread is sitting waiting for the Selector to select 
something. (at 
net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:252) 
The IO thread never wakes up.

Once the client enters this state, it's all over: every memcache client 
operation times out because the input queue is full. Because the add call in 
TCPMemcachedNodeImpl can't add to the queue, the selector is never woken up, 
and the client never recovers. The only thing to do in this case is shutdown() 
the current memcache client and throw it away.

It might be possible to fix this with a judicious application of finally inside 
MemcachedConnection.addOperation().
```

Original issue reported on code.google.com by `fiz...@gmail.com` on 1 Aug 2011 at 3:15

**Comment by iddolpm** [comment]
See also issue #176
